#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Thu Jul 10 11:54:15 BRT 2025
a=false
quark=true
create=true
refurbished_furniture=true
